import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Cursor from "./components/Cursor";
import Providers from  "./components/providers";
const inter = Inter({ subsets: ["latin"] });
// import { useSelectedTechs } from "./Home/page";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Cursor>
            {children}
          </Cursor>
        </Providers>
      </body>
    </html>
  );
}
